[Fix] Error building Odoo.sh line 38, in test_name_get
Date	Level	Type	Message
10/06/2024 14:56:18	ERROR	server	Table 'stock_picking': unable to set NOT NULL on column 'equipment_id'
10/06/2024 14:56:42	ERROR	server	FAIL: Subtest TestModelDeprecations.test_name_get (model='rs.stock.equipment')
Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/addons/base/tests/test_deprecation.py", line 38, in test_name_get
    self.fail(f"Deprecated name_get method found on {model_name} in {module.__name__}, you should override `_compute_display_name` instead")
AssertionError: Deprecated name_get method found on rs.stock.equipment in odoo.addons.rs_stock_equipment.models.rs_stock_equipment, you should override `_compute_display_name` instead
10/06/2024 15:20:23	ERROR	server	1 failed, 0 error(s) of 2024 tests when loading database 'aramirezpcvirgo-odoo-sh-main-13630348'
10/06/2024 14:56:18	WARNING	server	Two fields (equipment_stock_move_count, equipment_stock_move_line_count) of rs.stock.equipment() have the same label: Stock Moves. [Modules: rs_stock_equipment and rs_stock_equipment]
10/06/2024 14:56:23	WARNING	server	Missing `license` key in manifest for 'rs_stock_equipment', defaulting to LGPL-3